//@ui5-bundle ui5/walkthrough/Component-preload.js
sap.ui.predefine("ui5/walkthrough/Component", ["sap/ui/core/UIComponent","sap/ui/model/json/JSONModel","sap/ui/model/resource/ResourceModel"],(e,i,t)=>{"use strict";return e.extend("ui5.crud.Component",{metadata:{interfaces:["sap.ui.core.IAsyncContentCreation"],manifest:"json"},init(){e.prototype.init.apply(this,arguments);const i=new t({bundleName:"ui5.crud.i18n.i18n"});this.setModel(i,"i18n");this.getRouter().initialize()}})});
sap.ui.predefine("ui5/walkthrough/controller/App.controller", ["sap/ui/core/mvc/Controller","sap/ui/model/json/JSONModel","sap/ui/model/resource/ResourceModel"],(e,o,r)=>{"use strict";return e.extend("ui5.crud.controller.App",{onInit(){},_onPatternMatched:function(e){var o=e.getParameter("arguments");var r=o.id;console.log("Received ID: ",r)}})});
sap.ui.predefine("ui5/walkthrough/controller/Dashboard.controller", ["sap/ui/core/mvc/Controller","sap/ui/model/json/JSONModel","sap/ui/model/resource/ResourceModel","ui5/crud/customcontrols/CustomDataTable","sap/ui/model/Filter","sap/ui/model/FilterOperator","ui5/crud/services/ApiService"],(e,r,t,o,a,i,l)=>{"use strict";return e.extend("ui5.crud.controller.Dashboard",{onInit(){let e=this;var t=new r;t.loadData("./services/config.json");t.attachRequestCompleted(function(){var o=t.getProperty("/baseURL");var a=t.getProperty("/endpoints/getUsers");var i=o+a;l.makeAPICall(i).then(function(t){console.log(t);var o=new r;let a=[];for(let e=0;e<2;e++){a.push(t[e])}o.setData({data:a});e.getView().setModel(o)}.bind(this)).catch(function(e){console.error("API call failed",e)})})},onSearch:function(e){var r=this.byId("table");var t=e.getParameter("newValue");var o=null;if(t&&t.length>0){o=new sap.ui.model.Filter("name",sap.ui.model.FilterOperator.Contains,t)}var a=r.getBinding("rows");if(a){a.filter(o?[o]:[])}else{console.error("Table row binding is not available.")}}})});
sap.ui.predefine("ui5/walkthrough/controller/Header.controller", ["sap/ui/core/mvc/Controller","sap/ui/model/json/JSONModel","sap/ui/model/resource/ResourceModel"],(e,o,s)=>{"use strict";return e.extend("ui5.crud.controller.Header",{onInit(){jQuery.sap.includeStyleSheet("css/header.css")},onButtonPress:function(e){var o=e.getSource().getId();var s=o.split("--")[1];const t=this.getOwnerComponent().getRouter();switch(s){case"button1":t.navTo("dashboard");break;case"button2":t.navTo("userdetails",{id:123});break;case"button3":console.log("Button 3 pressed");break;default:console.log("Unknown button pressed")}},onExit:function(){jQuery('link[href="css/header.css"]').remove()}})});
sap.ui.predefine("ui5/walkthrough/controller/NotFound.controller", ["sap/ui/core/mvc/Controller"],function(n){"use strict";return n.extend("ui5.crud.controller.NotFound",{onInit:function(){}})});
sap.ui.predefine("ui5/walkthrough/customcontrols/CustomDataTable", ["sap/ui/core/Control","sap/ui/table/Table","sap/ui/table/Column","sap/m/Text","sap/m/ColumnListItem","sap/ui/model/json/JSONModel"],function(t,e,n,o,a){"use strict";return t.extend("ui5.crud.customcontrols.CustomDataTable",{metadata:{properties:{data:{type:"object",defaultValue:null}}},init:function(){this._sGlobalText=5;this._oTable=new e({})},renderer:function(t,e){t.write("<div>");t.renderControl(e._oTable);t.write("</div>")},setData:function(t){console.log(t);var e=t.map(function(t){return{...t,buttonText1:"Edit",buttonText2:"Delete",onClick1:function(){alert("Button 1 clicked for ")},onClick2:function(){alert("Button 2 clicked for ")}}});var n=new sap.ui.model.json.JSONModel;n.setData({rows:e});this._oTable.setModel(n);var o=new sap.ui.table.Column({label:new sap.m.Text({text:"Title"}),template:new sap.m.Text({text:"{name}"})});var a=new sap.ui.table.Column({label:new sap.m.Text({text:"Body"}),template:new sap.m.Text({text:"{age}"})});var l=new sap.ui.table.Column({label:new sap.m.Text({text:"Action"}),template:new sap.m.HBox({items:[new sap.m.Button({text:"{buttonText1}",press:"{onClick1}"}),new sap.m.Button({text:"{buttonText2}",press:"{onClick2}"})]})});this._oTable.setVisibleRowCount(t.length);this._oTable.addColumn(o);this._oTable.addColumn(a);this._oTable.addColumn(l);this._oTable.bindRows("/rows")},createColumns:function(t){}})});
sap.ui.predefine("ui5/walkthrough/services/ApiService", ["jquery.sap.global"],function(jQuery){"use strict";return{makeAPICall:function(n,t,e){t=t||"GET";return new Promise(function(i,u){jQuery.ajax({url:n,method:t,data:e?JSON.stringify(e):null,contentType:"application/json",success:function(n){i(n)},error:function(n){u(n)}})})}}});
sap.ui.require.preload({
	"ui5/walkthrough/i18n/i18n.properties":'# App Descriptor\r\nappTitle=OpenUI5 Crud\r\nappDescription=A simple crud app that explains the most important concepts of OpenUI5\r\n\r\n# Hello Panel\r\nshowHelloButtonText=Say Hello\r\nhelloMsg=Hello {0}\r\n\r\n# Detail Page\r\ndetailPageTitle=Crud - Details\r\n\r\nhomePageTitle=Hello Dashboard\r\n',
	"ui5/walkthrough/manifest.json":'{"_version":"1.65.0","sap.app":{"id":"ui5.walkthrough","i18n":{"bundleUrl":"i18n/i18n.properties","supportedLocales":[""]},"title":"{{appTitle}}","description":"{{appDescription}}","type":"application","applicationVersion":{"version":"1.0.0"}},"sap.ui":{"technology":"UI5","deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"dependencies":{"minUI5Version":"1.108.0","libs":{"sap.ui.core":{},"sap.m":{}}},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"ui5.crud.i18n.i18n","supportedLocales":[""],"fallbackLocale":""}}},"rootView":{"viewName":"ui5.crud.view.App","type":"XML","id":"app"},"resources":{"css":[{"uri":"css/style.css"}],"customcontrols":{"namespace":"ui5.crud.customcontrols"}},"routing":{"config":{"routerClass":"sap.m.routing.Router","type":"View","viewType":"XML","path":"ui5/crud/view","controlId":"app","controlAggregation":"pages","history":true,"transition":"slide","bypassed":{"target":"notFound"},"async":true},"routes":[{"pattern":"","name":"dashboard","target":"dashboard"},{"pattern":"userdetails/{id}","name":"userdetails","target":"userdetails"}],"targets":{"dashboard":{"id":"dashboard","name":"Dashboard","viewLevel":0},"userdetails":{"id":"userdetails","name":"UserDetails","viewLevel":1},"notFound":{"id":"notFound","name":"NotFound","transition":"show"}}},"resourceRoots":{"ui5.crud":"./"}}}',
	"ui5/walkthrough/view/NotFound.view.xml":'<mvc:View\r\n   controllerName="ui5.crud.controller.NotFound"\r\n   xmlns="sap.m"\r\n   xmlns:mvc="sap.ui.core.mvc"><MessagePage\r\n      title="{i18n>NotFound}"\r\n      text="{i18n>NotFound.text}"\r\n      description="{i18n>NotFound.description}"/></mvc:View>',
	"ui5/walkthrough/view/UserDetails.view.xml":'<mvc:View\r\n    controllerName="ui5.crud.controller.App"\r\n    xmlns="sap.m"\r\n    xmlns:mvc="sap.ui.core.mvc"\r\n    displayBlock="true"><VBox class="custom-container"><mvc:XMLView viewName="ui5.crud.view.components.Header" /><Text text="Hello UserDetails page"/></VBox></mvc:View>',
	"ui5/walkthrough/view/app.view.xml":'<mvc:View\r\n   controllerName="ui5.crud.controller.App"\r\n   xmlns="sap.m"\r\n   xmlns:mvc="sap.ui.core.mvc"><App class="myAppDemoWT" id="app"/></mvc:View>',
	"ui5/walkthrough/view/components/Header.view.xml":'<mvc:View\r\n    controllerName="ui5.crud.controller.header"\r\n    xmlns:mvc="sap.ui.core.mvc"\r\n    xmlns="sap.m"><App class="header-app"><pages><Page title="Responsive Header"><customHeader><Bar><contentLeft><Button \r\n                               icon="sap-icon://sap-logo-shape" \r\n                               press="onMenuPress" \r\n                               class="btn-header"\r\n                            /></contentLeft><contentMiddle><HBox class="header-container"><Link text="About Us"  press="onButtonPress" id="button1"/><Link text="User Detail" press="onButtonPress" id="button2"/><Link text="Access" press="onButtonPress" id="button3"/></HBox></contentMiddle><contentRight><Button \r\n                              icon="sap-icon://log" \r\n                              press="onLogoutPress"\r\n                              class="btn-header"\r\n                            /></contentRight></Bar></customHeader></Page></pages></App></mvc:View>\r\n',
	"ui5/walkthrough/view/dashboard.view.xml":'<mvc:View\r\n    controllerName="ui5.crud.controller.Dashboard"\r\n    xmlns="sap.m"\r\n    xmlns:mvc="sap.ui.core.mvc"\r\n    xmlns:custom="ui5.crud.customcontrols"\r\n    displayBlock="true"><VBox class="custom-container"><mvc:XMLView viewName="ui5.crud.view.components.Header" /><HBox><SearchField\r\n                      id="searchField"\r\n                      placeholder="Search..."\r\n                      liveChange="onSearch" \r\n                     /><Button\r\n                      text="Add New Data"\r\n                     /></HBox><Table id="apiTable" items="{/data}" visibleRowCount="1" height="400px"><columns><Column><Text text="ID"/></Column><Column><Text text="Title"/></Column><Column><Text text="Description"/></Column><Column><Text text="Action"/></Column></columns><items><ColumnListItem><cells><Text text="{id}"/><Text text="{title}"/><Text text="{body}"/><HBox><Button text="Edit"/><Button text="Delete"/></HBox></cells></ColumnListItem></items></Table></VBox></mvc:View>'
});
//# sourceMappingURL=Component-preload.js.map
